version: '3.8'
services:
  postgres:
    image: postgres
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=rohit
      - POSTGRES_PASSWORD=random123pw
  
  week27-project:
    build:
      network: host
      context: ./ 
      dockerfile: Dockerfile
    
    environment:
      - DATABASE_URL=postgresql://rohit:random123pw@postgres:5432/postgres
  
    ports:
      - 3000:3000
    depends_on:
      - postgres