name: Continuous Deployment (Prod) (Backend)
on:
  push:
    branches: [ main ]            # Trigger the workflow on push to the main branch
jobs:
  build:                          # Job Name
    runs-on: ubuntu-latest        # Ubuntu OS is used for the job
    steps:
      - name: Checkout code
        uses: actions/checkout@v2 # Checkout the code in the main branch on Ubuntu OS
        with:                     # Git Module Configuration
            fetch-depth: 0        # Shallow clones should be disabled for a better tag resolution
      
      - name: Docker Hub login                          # Login to Docker Hub
        uses: docker/login-action@v2                    # Docker Login Action
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}   
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      
      - name: Build and push                            # Build and push the Docker image to Docker Hub
        uses: docker/build-push-action@v4                     
        with:                                           # Docker Build and Push Configuration
          context: .                                    # Docker Build Context
          file: ./docker/Dockerfile.backend             # Dockerfile Path
          push: true                      
          tags: 100xdevs/user-app-backend:${{ github.sha }}     # Docker Image Tag